
substitutions:
  devicename: m5stickc
  upper_devicename: M5StickC

esphome:
  name: $devicename
  friendly_name: m5stickc+
  platformio_options:
    upload_speed: 115200

esp32:
  board: m5stick-c
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR API KEY HERE"

ota:
  password: "YOUR OTA PASS HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5StickC Fallback Hotspot"
    password: "YOUR FALLBACK AP PASSWORD"

captive_portal:

web_server:

external_components:
  - source:
      type: git
      url: https://github.com/airy10/esphome-m5stickC/
    components: [ axp192 ]
  - source: github://pr#4105
    components: [ display_menu_base, graphical_display_menu, display, graph] #font ]

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - display_menu.enter:
#    on_release:
#      then:
#        - light.turn_off: led1
        
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - display_menu.down:

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "M5Stick Battery Level"
      id: "m5stick_batterylevel"

  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: wifi_dbm
  - platform: uptime
    name: ${upper_devicename} Uptime

# internal LED
light:
  - platform: monochromatic
    output:  builtin_led
    name: ${upper_devicename} Led
    id: led1

output:
  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

# internal IR Transmitter
remote_transmitter:
  - pin:
      number: GPIO9
    carrier_duty_percent: 50%
    id: my_internal_transmitter

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True

# builtin 135x240 TFT
display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    id: my_display
    pages:
      - id: menu_page
        lambda: |-
          const auto display_width = it.get_width();
          const auto display_height = it.get_height();

          it.print(0, 0, id(font3), COLOR_ON, TextAlign::TOP_LEFT, "Other drawing example");

          const auto font_height = 20;
          it.menu(0, font_height, id(my_menu), display_width , display_height - font_height);

font:
  - file: 'arial.ttf'
    id: font1
    size: 8

  - file: 'arial.ttf'
    id: font2
    size: 36

  - file: 'arial.ttf'
    id: font3
    size: 14

graphical_display_menu:
  id: my_menu
  display: my_display
  # Optional: You'll want this to trigger the drawing of the lambda
  on_redraw:
    then:
      component.update: my_display
  font: font2
  active: true
## Edit Items to your liking
  items:
    - type: label
      text: Normal label
    - type: menu
      text: Child Menu
      items:
        - type: label
          text: A child menu item
        - type: back
          text: Back 
##
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    id: sntp_time
